# constants
pos_tag = ('UNKNOWN', 'ADJ', 'ADP', 'ADV', 'CONJ', 'DET', 'NOUN', 'NUM',
           'PRON', 'PRT', 'PUNCT', 'VERB', 'X', 'AFFIX')
pos_aspect = ('ASPECT_UNKNOWN', 'PERFECTIVE', 'IMPERFECTIVE', 'PROGRESSIVE')
pos_case = ('CASE_UNKNOWN', 'ACCUSATIVE', 'ADVERBIAL', 'COMPLEMENTIVE', 'DATIVE',
            'GENITIVE', 'INSTRUMENTAL', 'LOCATIVE', 'NOMINATIVE', 'OBLIQUE', 'PARTITIVE',
            'PREPOSITIONAL', 'REFLEXIVE_CASE', 'RELATIVE_CASE', 'VOCATIVE')
pos_form = ('FORM_UNKNOWN', 'ADNOMIAL', 'AUXILIARY', 'COMPLEMENTIZER', 'FINAL_ENDING', 'GERUND',
            'REALIS', 'IRREALIS', 'SHORT', 'LONG', 'ORDER', 'SPECIFIC')
pos_gender = ('GENDER_UNKNOWN', 'FEMININE', 'MASCULINE', 'NEUTER')
pos_mood = ('MOOD_UNKNOWN', 'CONDITIONAL_MOOD', 'IMPERATIVE', 'INDICATIVE', 'INTERROGATIVE',
            'JUSSIVE', 'SUBJUNCTIVE')
pos_number = ('NUMBER_UNKNOWN', 'SINGULAR', 'PLURAL', 'DUAL')
pos_person = ('PERSON_UNKNOWN', 'FIRST', 'SECOND', 'THIRD', 'REFLEXIVE_PERSON')
pos_proper = ('PROPER_UNKNOWN', 'PROPER', 'NOT_PROPER')
pos_reciprocity = ('RECIPROCITY_UNKNOWN', 'RECIPROCAL', 'NON_RECIPROCAL')
pos_tense = ('TENSE_UNKNOWN', 'CONDITIONAL_TENSE', 'FUTURE', 'PAST', 'PRESENT', 'IMPERFECT', 'PLUPERFECT')
pos_voice = ('VOICE_UNKNOWN', 'ACTIVE', 'CAUSATIVE', 'PASSIVE')
dependency_label = ('UNKNOWN','ABBREV','ACOMP','ADVCL','ADVMOD','AMOD','APPOS','ATTR','AUX','AUXPASS','CC',
                    'CCOMP','CONJ','CSUBJ','CSUBJPASS','DEP','DET','DISCOURSE','DOBJ','EXPL','GOESWITH','IOBJ',
                    'MARK','MWE','MWV','NEG','NN','NPADVMOD','NSUBJ','NSUBJPASS','NUM','NUMBER','P','PARATAXIS',
                    'PARTMOD','PCOMP','POBJ','POSS','POSTNEG','PRECOMP','PRECONJ','PREDET','PREF','PREP','PRONL',
                    'PRT','PS','QUANTMOD','RCMOD','RCMODREL','RDROP','REF','REMNANT','REPARANDUM','ROOT','SNUM',
                    'SUFF','TMOD','TOPIC','VMOD','VOCATIVE','XCOMP','SUFFIX','TITLE','ADVPHMOD','AUXCAUS','AUXVV',
                    'DTMOD','FOREIGN','KW','LIST','NOMC','NOMCSUBJ','NOMCSUBJPASS','NUMC','COP','DISLOCATED','ASP',
                    'GMOD','GOBJ','INFMOD','MES','NCOMP')
